version: '3.8'
networks:
  ms-network:
    external: true
services:
  ms-gateway:
    container_name: ms-gateway
    image: ms-gateway-development
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - '${API_PORT}:${API_PORT}'
    networks:
      - ms-network
    command: npx nest start --watch
